# Generated by Django 3.1.6 on 2021-03-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeframetype',
            name='current_end_date',
        ),
        migrations.RemoveField(
            model_name='timeframetype',
            name='current_start_date',
        ),
    ]
