# Generated by Django 3.1.6 on 2021-03-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210329_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeframetype',
            name='recurrence_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
