# Generated by Django 3.1.6 on 2021-03-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210224_0024'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timeframetype',
            table='timeframe_types',
        ),
    ]
