# Generated by Django 3.1.6 on 2021-03-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210224_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportschedule'),
        ),
        migrations.AlterModelTable(
            name='timeframetype',
            table='timeframe_types',
        ),
    ]
