# Generated by Django 3.1.6 on 2021-03-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210313_0036'),
        ('api', '0003_auto_20210315_1649'),
    ]

    operations = [
    ]
