# Generated by Django 3.1.6 on 2021-04-02 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210329_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScheduleAddin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_dictionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reportingdictionary')),
            ],
            options={
                'db_table': 'report_schedule_addins',
            },
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='addin_foodbank_report',
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='addin_state_report',
        ),
        migrations.AlterField(
            model_name='datadefinition',
            name='interpretation_notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='date_scheduled',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_scope_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ReportScheduleAddinReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportschedule')),
                ('report_schedule_addin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportscheduleaddin')),
            ],
            options={
                'db_table': 'report_schedule_addin_reports',
            },
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='addin_reports',
            field=models.ManyToManyField(blank=True, through='api.ReportScheduleAddinReport', to='api.ReportScheduleAddin'),
        ),
    ]
