# Generated by Django 3.1.6 on 2021-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210402_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportschedule',
            name='report_scope_value',
            field=models.PositiveBigIntegerField(),
        ),
    ]
