# Generated by Django 3.1.6 on 2021-03-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20210317_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframetype',
            name='recurrence_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
