# Generated by Django 3.1.6 on 2021-03-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_timeframetype_recurrence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportschedule',
            name='report_scope_value',
            field=models.CharField(max_length=255),
        ),
    ]
