# Generated by Django 3.1.6 on 2021-04-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210402_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='no_data',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datadefinition',
            name='interpretation_notes',
            field=models.TextField(blank=True),
        ),
    ]
