# Generated by Django 3.1.6 on 2021-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210402_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadefinition',
            name='calculation_notes',
            field=models.TextField(blank=True),
        ),
    ]
